apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kopefalva
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kopefalva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: molnarimi0211/k8s:frontend-10
          ports:
            - containerPort: 80
